---
# Use `crc start --log-level debug` to debug issues
- name: Start the instance
  ansible.builtin.command: crc start
  register: result
  changed_when: not "already running" in result.stderr

- name: Debug output
  ansible.builtin.debug:
    var: result.stdout_lines

# Set environment information
# eval $(crc oc-env)

- name: Login to OpenShift
  ansible.builtin.command: oc login -u kubeadmin https://api.crc.testing:6443
  register: result
  changed_when: false

- name: Open the OpenShift Web Console in the default browser
  ansible.builtin.command: crc console --credentials
  register: result
  changed_when: false
