---
- name: Show details about the running instance
  ansible.builtin.command: crc status -o json
  changed_when: false
  register: result

- name: Debug results
  ansible.builtin.debug:
    var: result

# - Status on OpenShift objects

# ```bash
# oc get nodes
# oc get projects
# oc get operators --all-namespaces
# oc get pods
# oc get clusteroperators --all-namespaces
# ```