---
# Use `crc start --log-level debug` to debug issues
- name: Start the instance
  command: crc start
  register: result
  changed_when: not "already running" in result.stderr

- debug:
    var: result.stdout_lines

- name: Create bash completion for `oc` command
  command: oc completion bash > /usr/local/etc/bash_completion.d/
    creates: "/usr/local/etc/bash_completion.d/oc_bash_completion"
  register: result
  changed_when: false

# Set environment information
# eval $(crc oc-env)

- name: Login to OpenShift
  command: oc login -u kubeadmin https://api.crc.testing:6443
  register: result
  changed_when: false

- name: Open the OpenShift Web Console in the default browser
  command: crc console --credentials
  register: result
  changed_when: false
