---
- name: Show details about the running instance
  command: crc status -o json
  register: result

- debug:
    var: result

# - Status on OpenShift objects

# ```bash
# oc get nodes
# oc get projects
# oc get operators --all-namespaces
# oc get pods
# oc get clusteroperators --all-namespaces
# ```