---
- name: Delete instance of OpenShift Local
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Delete
      ansible.builtin.include_role:
        name: crc
        tasks_from: delete