---
- name: Prepare OpenShift Local
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Prepare
      ansible.builtin.include_role:
        name: crc
        tasks_from: prepare