---
- name: Start OpenShift Local
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Start
      ansible.builtin.include_role:
        name: crc
        tasks_from: start